title: Belintawati Zelda Br Ginting
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > 
  Fresh Graduate
  <br><br>
  Ilmu Komputer 
  <br><br>
  <a href="https://www.linkedin.com/in/belintawati-zelda-br-g-ba470725a/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal
google_analytics: UA-000000-0 
